services:
  python_telegram_bot:
    build:
      context: ./python_telegram_bot
    restart: unless-stopped
    env_file:
      - ./python_telegram_bot/.env
    volumes:
      - ./python_telegram_bot/data:/app/data

